Addy Abid - String Manipulation 2
AddyAbid/c1021-code-solutions pull request #60
Opened 2021-11-02 00:56 UTC by AddyAbid

![_Users_addyabid_repos_c1021-code-solutions_string-manipulation-2_index html](https://user-images.githubusercontent.com/85080021/139769813-cda76e25-75a6-45fe-a24b-adae42524f7b.png)

2021-11-02 23:30 UTC, codingcodymiller requested changes

2021-11-02 23:30 UTC, codingcodymiller commented on string-manipulation-2/src/capitalize-words.js
> +    var outPut = word.join(' ');
You should do this after the loop has ended

2021-11-02 23:30 UTC, codingcodymiller commented on string-manipulation-2/src/capitalize-word.js
> +  }
You should check for this before you do any other work, so you don't do things you don't end up using

2021-11-02 23:30 UTC, codingcodymiller commented on string-manipulation-2/src/num-vowels.js
> +      outPut += string[i].length;
Why the length? You should just add `1`

2021-11-03 00:14 UTC, AddyAbid commented
![_Users_addyabid_repos_c1021-code-solutions_string-manipulation-2_index html (1)](https://user-images.githubusercontent.com/85080021/139968699-1b6e6394-1257-483c-bf07-5ad5778f84ad.png)

2021-11-03 22:33 UTC, codingcodymiller approved these changes

2021-11-04 00:07 UTC, merged